/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Registro;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Oferta;
import vista.EliminarOferta;
import vista.ModificarOferta;

/**
 *
 * @author hecto
 */
public class ListaOferta extends javax.swing.JFrame {

    private static ListaOferta instancia;
    private DefaultTableModel tableModel;
    private int selectedCod;
    private ArrayList<Oferta> ofertas = new ArrayList<>();
    
    public static ListaOferta getInstancia(){
        if(instancia == null){
            instancia = new ListaOferta();
        }
        return instancia;
    }
    public ListaOferta() {
        initComponents();
         LlenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModificar = new javax.swing.JButton();
        jBuscador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaOfertas = new javax.swing.JTable();
        jNombreBuscarOferta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JToggleButton();
        btnEnviarOferta = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscadorActionPerformed(evt);
            }
        });

        jtListaOfertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Oferta", "Nombre", "Descripcion", "Fecha de Termino"
            }
        ));
        jScrollPane1.setViewportView(jtListaOfertas);

        jNombreBuscarOferta.setText("Buscar Ofertas:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Gestion de Ofertas");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEnviarOferta.setText("Enviar Oferta");
        btnEnviarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarOfertaActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Buscar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Limpiar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNombreBuscarOferta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnviarOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVolver)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnVolver)
                            .addComponent(btnEnviarOferta))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombreBuscarOferta)
                    .addComponent(jBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        if(jtListaOfertas.getSelectedRow() == -1)
        {
             JOptionPane.showMessageDialog(null, "Seleccione una oferta antes de escoger una acción.");
        }
        else
        {
            selectedCod = Integer.parseInt( jtListaOfertas.getValueAt(jtListaOfertas.getSelectedRow(), 0).toString());     
            ModificarOferta c = ModificarOferta.getInstancia(Registro.ObtenerOferta(selectedCod));
            c.setVisible(true);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void jBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscadorActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        AgregarOferta v = AgregarOferta.getInstancia();
        v.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        if(jtListaOfertas.getSelectedRow() == -1)
        {
             JOptionPane.showMessageDialog(null, "Seleccione una oferta antes de escoger una acción.");
        }
        else
        {
            selectedCod = Integer.parseInt( jtListaOfertas.getValueAt(jtListaOfertas.getSelectedRow(), 0).toString());     
            EliminarOferta c = EliminarOferta.getInstancia(Registro.ObtenerOferta(selectedCod));
            c.setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEnviarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarOfertaActionPerformed
        
        if(jtListaOfertas.getSelectedRow() == -1)
        {
             JOptionPane.showMessageDialog(null, "Seleccione una oferta antes de escoger una acción.");
        }
        else
        {
            selectedCod = Integer.parseInt( jtListaOfertas.getValueAt(jtListaOfertas.getSelectedRow(), 0).toString());     
            EnviarOferta c = EnviarOferta.getInstancia(Registro.ObtenerOferta(selectedCod));
            c.setVisible(true);
        }
    }//GEN-LAST:event_btnEnviarOfertaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
          String busqueda = jBuscador.getText();
          FiltrarTabla(busqueda);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
         jBuscador.setText(null);
        LlenarTabla();
    }//GEN-LAST:event_jToggleButton2ActionPerformed
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaOferta().setVisible(true);
            }
        });
    }
    
    public void LlenarTabla(){
        Object[][] data = {};
        String[] columnNames = {"Código#", "Titulo", "Descripción","Fecha término"};
        tableModel = new DefaultTableModel(data,columnNames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableModel.setRowCount(0);
        ofertas = Registro.ObtenerListaOfertas();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        //ArrayList<Oferta> lista = Registro.ObtenerListaProductos();
        Object[] registro = new Object[4];
        
        for (Oferta oferta : ofertas) {
            
            Oferta ofer = oferta;
            registro[0] = ofer.getCod_oferta();
            registro[1] = ofer.getTit_oferta();
            registro[2] = ofer.getDesc_oferta();
            registro[3] = formato.format(ofer.getFecha_termino());
            
            tableModel.addRow(registro);
        }

        jtListaOfertas.setModel(tableModel);
    }
    public void FiltrarTabla(String busqueda){
        DefaultTableModel model = tableModel;
        Registro reg = new Registro();
        model.setRowCount(0);
        ArrayList<Oferta> lista = Registro.ObtenerListaOfertasFiltrada(busqueda);
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Object[] registro = new Object[4];
        
        for (Oferta oferta : lista) {
            
            Oferta ofer = oferta;
            registro[0] = ofer.getCod_oferta();
            registro[1] = ofer.getTit_oferta();
            registro[2] = ofer.getDesc_oferta();
            registro[3] = formato.format(ofer.getFecha_termino());
            
            model.addRow(registro);
        }
        jtListaOfertas.getColumnModel().getColumn(0).setWidth(20);

        jtListaOfertas.setModel(model);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JToggleButton btnEnviarOferta;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField jBuscador;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNombreBuscarOferta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable jtListaOfertas;
    // End of variables declaration//GEN-END:variables
}
